# Generated by Django 5.2.1 on 2025-06-24 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de Profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='elearning_users_groups', related_query_name='elearning_user_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='elearning_users_permissions', related_query_name='elearning_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ModuleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='elearning.module', verbose_name='Module de formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur inscrit')),
            ],
            options={
                'verbose_name': 'Inscription au Module',
                'verbose_name_plural': 'Inscriptions aux Modules',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
