# Generated by Django 5.2.1 on 2025-06-24 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_utilisateur_profile_picture_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_question', models.TextField(verbose_name='Texte de la question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='image_module',
            field=models.ImageField(blank=True, null=True, upload_to='module_covers/', verbose_name='Image de couverture du module'),
        ),
        migrations.CreateModel(
            name='ContenuModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du contenu')),
                ('type_contenu', models.CharField(choices=[('texte', 'Texte / Leçon'), ('video', 'Vidéo'), ('quiz', 'Quiz'), ('document', 'Document (PDF, Word, Image, etc.)')], max_length=20, verbose_name='Type de contenu')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du contenu')),
                ('contenu_textuel', models.TextField(blank=True, null=True, verbose_name="Contenu textuel (pour type 'texte')")),
                ('url_video', models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de la vidéo (pour type 'video')")),
                ('fichier_document', models.FileField(blank=True, null=True, upload_to='module_documents/', verbose_name='Fichier du document (PDF, Word, Image, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='elearning.module', verbose_name='Module parent')),
            ],
            options={
                'verbose_name': 'Contenu de Module',
                'verbose_name_plural': 'Contenus de Modules',
                'ordering': ['module', 'ordre'],
                'unique_together': {('module', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='ChoixReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_choix', models.CharField(max_length=500, verbose_name='Texte du choix')),
                ('est_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='elearning.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix de Réponse',
                'verbose_name_plural': 'Choix de Réponses',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du quiz')),
                ('description', models.TextField(blank=True, verbose_name='Description du quiz')),
                ('score_minimum', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score minimum pour réussir (%)')),
                ('duree_limite_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée limite (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenu_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='elearning.contenumodule', verbose_name='Contenu de module (Quiz)')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elearning.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='ResultatQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_obtenu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score obtenu (%)')),
                ('reussi', models.BooleanField(default=False, verbose_name='Réussi')),
                ('date_tentative', models.DateTimeField(auto_now_add=True, verbose_name='Date de la tentative')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elearning.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Résultat de Quiz',
                'verbose_name_plural': 'Résultats de Quiz',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_certification', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Code de certification')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_emis', to='elearning.module', verbose_name='Module certifié')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('contenu_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_utilisateurs', to='elearning.contenumodule', verbose_name='Contenu du module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_contenus', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Progression du Contenu',
                'verbose_name_plural': 'Progression des Contenus',
                'unique_together': {('user', 'contenu_module')},
            },
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField(blank=True, null=True, verbose_name='Réponse textuelle (si applicable)')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='Date de la réponse')),
                ('est_correct', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.choixreponse', verbose_name='Choix sélectionné')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_utilisateurs', to='elearning.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réponse Utilisateur',
                'verbose_name_plural': 'Réponses Utilisateur',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
